name: "Deploy production and preview website"
description: "Deploys a built website artifact to a production and preview environment via SSH, with optional link checking."
author: "OpenRail Association"
branding:
  icon: upload-cloud
  color: purple

inputs:
  artifact_name:
    description: "The name of the uploaded artifact to deploy."
    required: true

  domain_preview:
    description: "Domain name for the preview deployment."
    required: true

  ssh_host:
    description: "SSH hostname (e.g. uberspace1.example.org)"
    required: true

  ssh_user:
    description: "SSH username"
    required: true

  ssh_port:
    description: "SSH port"
    required: false
    default: "22"

  ssh_timeout:
    description: "SSH connection timeout (e.g. 1m)"
    required: false
    default: "1m"

  ssh_command_timeout:
    description: "SSH command timeout (e.g. 2m)"
    required: false
    default: "2m"

  ssh_rm:
    description: "Remove remote directory before deploying (true/false)"
    required: false
    default: "true"

  ssh_strip_components:
    description: "How many path components to strip (for tar/scp unpacking)"
    required: false
    default: "1"

  dir_base:
    description: "Remote base directory (e.g. /var/www/virtual)"
    required: true

  dir_production:
    description: "Full path for production deployment"
    required: true

  dir_preview_base:
    description: "Preview base domain (e.g. preview.example.com)"
    required: true

  dir_preview_subdir:
    description: "Preview subdir (e.g. pr-123)"
    required: true

  linkchecker_enabled:
    description: "Enable link checker (true/false)"
    required: false
    default: "true"

  linkchecker_exclude:
    description: "Comma-separated list of domains to exclude from link checker"
    required: false
    default: ""

  linkchecker_include_fragments:
    description: "Include anchor fragments in link checking"
    required: false
    default: "true"

  linkchecker_max_concurrency:
    description: "Max concurrent requests for link checker"
    required: false
    default: "1"

  linkchecker_user_agent:
    description: "User-Agent for link checking"
    required: false
    default: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)..."

  linkchecker_retry_times:
    description: "Retry delay in seconds for link checking"
    required: false
    default: "5"

  linkchecker_fail_on_errors:
    description: "Fail workflow on link check errors (true/false)"
    required: false
    default: "false"

  sticky_comment_enabled:
    description: "Whether to enable sticky comments for the pull request. Defaults to true."
    required: false
    default: "true"

  step_summary_enabled:
    description: "Whether to enable step summaries in the GitHub Actions UI. Defaults to true."
    required: false
    default: "true"

runs:
  using: "workflow"
  main: ".github/workflows/deploy.yml"
