# SPDX-FileCopyrightText: 2025 DB Systel GmbH
#
# SPDX-License-Identifier: Apache-2.0

# This is the core of the action with all the inputs and logic for deploying a website.
# It can be called from other workflows or used directly in a workflow file.
# It handles both production and preview deployments, including link checking and sticky comments.
# It also supports removing the preview when a pull request is closed or merged.

name: Deploy Production and Preview

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      condition_production:
        required: true
        type: boolean
      domain_production:
        required: true
        type: string
      domain_preview:
        required: true
        type: string
      dir_base:
        required: true
        type: string
      dir_production:
        required: true
        type: string
      dir_preview_base:
        required: true
        type: string
      dir_preview_subdir:
        required: true
        type: string
      ssh_host:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      ssh_port:
        required: false
        default: 22
        type: number
      ssh_timeout:
        required: false
        default: "1m"
        type: string
      ssh_command_timeout:
        required: false
        default: "2m"
        type: string
      ssh_rm:
        required: false
        default: true
        type: boolean
      ssh_strip_components:
        required: false
        default: 1
        type: number
      linkchecker_enabled:
        required: false
        default: true
        type: boolean
      linkchecker_exclude:
        required: false
        default: ""
        type: string
      linkchecker_include_fragments:
        required: false
        default: true
        type: boolean
      linkchecker_max_concurrency:
        required: false
        default: 1
        type: number
      linkchecker_user_agent:
        required: false
        default: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
        type: string
      linkchecker_retry_times:
        required: false
        default: 5
        type: number
      linkchecker_fail_on_errors:
        required: false
        default: false
        type: boolean
      sticky_comment_enabled:
        required: false
        default: true
        type: boolean
      step_summary_enabled:
        required: false
        default: true
        type: boolean
    secrets:
      ssh_key:
        required: true
    outputs:
      production_url:
        description: "The URL of the deployed production website"
        value: ${{ jobs.deploy-production.outputs.production_url }}
      preview_url:
        description: "The URL of the deployed preview website"
        value: ${{ jobs.deploy-preview.outputs.preview_url }}

jobs:
  vars:
    runs-on: ubuntu-24.04
    outputs:
      pr_closed_merged: ${{ steps.pr_status.outputs.pr_closed_merged }}
      datetime: ${{ steps.datetime.outputs.datetime }}
      linkchecker_fragments: ${{ steps.linkchecker_fragments.outputs.linkchecker_fragments }}
      linkchecker_exclude: ${{ steps.linkchecker_exclude.outputs.linkchecker_exclude }}
    steps:
      - id: pr_status
        run: echo "pr_closed_merged=${{ github.event.pull_request.closed_at || github.event.pull_request.merged }}" >> "$GITHUB_OUTPUT"

      - id: datetime
        run: echo "datetime=$(date '+%Y-%m-%d %H:%M:%S %Z')" >> "$GITHUB_OUTPUT"

      - id: linkchecker_fragments
        run: |
          if [ "${{ inputs.linkchecker_include_fragments }}" == 'true' ]; then
            echo "linkchecker_fragments=--include-fragments" >> "$GITHUB_OUTPUT"
          else
            echo "linkchecker_fragments=" >> "$GITHUB_OUTPUT"
          fi

      - id: linkchecker_exclude
        run: |
          if [ -n "${{ inputs.linkchecker_exclude }}" ]; then
            excludes=$(echo "${{ inputs.linkchecker_exclude }}" | sed 's/,/ --exclude /g; s/^/--exclude /')
            echo "linkchecker_exclude=$excludes" >> "$GITHUB_OUTPUT"
          else
            echo "linkchecker_exclude=" >> "$GITHUB_OUTPUT"
          fi

  linkchecker:
    runs-on: ubuntu-24.04
    needs: vars
    if: inputs.linkchecker_enabled == true && (needs.vars.outputs.pr_closed_merged == '' || needs.vars.outputs.pr_closed_merged == 'false')
    steps:
      - name: Download artifact for production link check to .
        uses: actions/download-artifact@v4
        if: inputs.condition_production
        with:
          name: ${{ inputs.artifact_name }}
          path: .

      - name: Download artifact for preview link check to subdirectory
        uses: actions/download-artifact@v4
        if: github.event.pull_request
        with:
          name: ${{ inputs.artifact_name }}
          path: ./${{ inputs.dir_preview_subdir }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            -r ${{ inputs.linkchecker_retry_times }}
            -u "${{ inputs.linkchecker_user_agent }}"
            ${{ needs.vars.outputs.linkchecker_fragments }}
            ${{ needs.vars.outputs.linkchecker_exclude }}
            --max-concurrency ${{ inputs.linkchecker_max_concurrency }}
            --root-dir ${{ github.workspace }}
            .
          fail: ${{ inputs.linkchecker_fail_on_errors }}

  # Deployment jobs
  deploy-production:
    runs-on: ubuntu-24.04
    needs:
      - vars
    outputs:
      production_url: ${{ steps.send_url.outputs.production_url }}
    env:
      url: ${{ inputs.domain_production }}
    # Only deploy if production condition is met and not a closed/merged pull request
    if: inputs.condition_production && (needs.vars.outputs.pr_closed_merged == '' || needs.vars.outputs.pr_closed_merged == 'false')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./${{ inputs.artifact_name }}

      - name: Copy website to host
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          host: ${{ inputs.ssh_host }}
          username: ${{ inputs.ssh_user }}
          key: ${{ secrets.ssh_key }}
          port: ${{ inputs.ssh_port }}
          timeout: ${{ inputs.ssh_timeout }}
          command_timeout: ${{ inputs.ssh_command_timeout }}
          target: ${{ inputs.dir_base }}/${{ inputs.dir_production }}/
          source: "${{ inputs.artifact_name }}/*"
          rm: ${{ inputs.ssh_rm }}
          strip_components: ${{ inputs.ssh_strip_components }}

      - name: Add step summary
        if: inputs.step_summary_enabled == true
        run: |
          SUMMARY=$'# Website Deployment Summary\nDeployed website to production ${{ env.url }}'
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      - name: Send URL to output
        id: send_url
        run: echo "production_url=${{ env.url }}" >> $GITHUB_OUTPUT

  deploy-preview:
    runs-on: ubuntu-24.04
    needs:
      - vars
    outputs:
      preview_url: ${{ steps.send_url.outputs.preview_url }}
    env:
      url: ${{ inputs.domain_preview }}/${{ inputs.dir_preview_subdir }}
    # Only deploy if non-closed/non-merged pull request
    if: github.event.pull_request && needs.vars.outputs.pr_closed_merged == 'false'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./${{ inputs.artifact_name }}

      - name: Copy website to host
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          host: ${{ inputs.ssh_host }}
          username: ${{ inputs.ssh_user }}
          key: ${{ secrets.ssh_key }}
          port: ${{ inputs.ssh_port }}
          timeout: ${{ inputs.ssh_timeout }}
          command_timeout: ${{ inputs.ssh_command_timeout }}
          target: ${{ inputs.dir_base }}/${{ inputs.dir_preview_base }}/${{ inputs.dir_preview_subdir }}/
          source: "${{ inputs.artifact_name }}/*"
          rm: ${{ inputs.ssh_rm }}
          strip_components: ${{ inputs.ssh_strip_components }}

      - name: Inform about Preview URL
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        if: inputs.sticky_comment_enabled == true
        with:
          header: pr-preview
          message: |
            Pull Request Live Preview
            :---:
            | <p><br />:rocket: View preview at <br />${{ env.url }}/<br /><br /></p>
            | <p>Last updated: ${{ needs.vars.outputs.datetime }}</p>

      - name: Add step summary
        if: inputs.step_summary_enabled == true
        run: |
          SUMMARY=$'# Website Deployment Summary\nDeployed preview website to ${{ env.url }}'
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      - name: Send URL to output
        id: send_url
        run: echo "preview_url=${{ env.url }}" >> $GITHUB_OUTPUT

  remove-preview:
    runs-on: ubuntu-24.04
    needs:
      - vars
    env:
      url: ${{ inputs.domain_preview }}/${{ inputs.dir_preview_subdir }}
    # Only deploy if non-closed/non-merged pull request
    if: github.event.pull_request && needs.vars.outputs.pr_closed_merged != 'false'
    steps:
      - name: Create deletion notice
        run: mkdir -p ${{ inputs.artifact_name }} && echo "This PR has been closed or merged. The preview has been removed." > ${{ inputs.artifact_name }}/index.html

      - name: Copy empty folder to host
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          host: ${{ inputs.ssh_host }}
          username: ${{ inputs.ssh_user }}
          key: ${{ secrets.ssh_key }}
          port: ${{ inputs.ssh_port }}
          timeout: ${{ inputs.ssh_timeout }}
          command_timeout: ${{ inputs.ssh_command_timeout }}
          target: ${{ inputs.dir_base }}/${{ inputs.dir_preview_base }}/${{ inputs.dir_preview_subdir }}/
          source: "${{ inputs.artifact_name }}/*"
          rm: ${{ inputs.ssh_rm }}
          strip_components: ${{ inputs.ssh_strip_components }}

      - name: Inform about preview removal
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        if: inputs.sticky_comment_enabled == true
        with:
          header: pr-preview
          message: |
            Pull Request Live Preview
            :---:
            | <p><br />:x: Preview has been removed.<br /><br /></p>

      - name: Add step summary
        if: inputs.step_summary_enabled == true
        run: |
          SUMMARY=$'# Website Deployment Summary\nRemoved preview website at ${{ env.url }}'
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
