# SPDX-FileCopyrightText: 2025 DB Systel GmbH
#
# SPDX-License-Identifier: Apache-2.0

name: Selftest Action

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - main

permissions:
  contents: read

env:
  ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
  dir_preview_subdir: "webdeploy-pr-${{ github.event.number }}"
  condition_production: ${{ github.ref == 'refs/heads/main' }}

jobs:
  build:
    name: Build Website (Placeholder)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build website
        env:
          GH_REF: ${{ github.ref }}
          GH_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "Simulating build..."
          mkdir -p dist
          echo "<html><body>
          <p>Hello world: <a href="https://openrailassociation.org">LINK 1</a></p>
          <p>Don't linkcheck me: <a href="https://example.com">LINK 2</a></p>
          <p>Relative link: <a href="foobar.html">LINK 3</a></p>
          <p>${GH_REF}.${GH_PR_HEAD_SHA}</p>
          </body></html>" > dist/index.html
          echo "baz" > dist/foobar.html

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: website
          path: dist

  deploy:
    name: Web Deployment
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Call action locally
        uses: ./
        with:
          artifact_name: website
          condition_production: ${{ env.condition_production }}
          domain_production: https://web-deployment-action.openrailassociation.org
          domain_preview: https://web-preview.openrailassociation.org
          dir_base: "/var/www/virtual/openrail"
          dir_production: "web-deployment-action.openrailassociation.org"
          dir_preview_base: "web-preview.openrailassociation.org"
          dir_preview_subdir: ${{ env.dir_preview_subdir }}
          ssh_host: uberspace1.openrailassociation.org
          ssh_user: openrail
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          linkchecker_exclude: "example.com,example.org"
          linkchecker_include_fragments: true
          linkchecker_verbose: true
          linkchecker_extra_args: "--index-files index.html"
          gh_deployment: "preview"
